/* eslint-disable */
/** Auto-generated by scripts/generate-asset-manifest.mjs — do not edit manually. */
export const GENERATED_ASSET_MANIFEST = {
  "homeTypes": {
    "bungalow": "/assets/bungalow.PNG",
    "duplexSuplex": "/assets/duplex-suplex.jpeg",
    "duplex": "/assets/duplex.PNG",
    "investment": "/assets/investment-property.PNG",
    "multi_family": "/assets/multi-family.PNG",
    "apartments": "/assets/lifestyle/apartments.jpg",
    "villa": "/assets/lifestyle/villa.jpg"
  },
  "styles": {
    "afro_modern": "/assets/ambience/afro-modern.jpeg",
    "classic_nigerian": "/assets/lifestyle/classic-nigerian.jpg",
    "contemporary_luxury": "/assets/ambience/luxury-contemporary.jpeg",
    "eco_friendly": "/assets/lifestyle/eco-friendly.jpg",
    "modern_tropical": "/assets/lifestyle/modern-tropical.jpg"
  },
  "hero": "/assets/lifestyle/hero.jpg"
} as const;
