import type {
  ContractorBid,
  ContractorDocument,
  ContractorMilestone,
  ContractorNotification,
  ContractorProfile,
  ContractorProject,
  ContractorReview,
  ContractorUpdate,
  ContractorVault,
  MarketplaceArtisan,
  MarketplaceProject,
  TeamMember,
} from "./types";

export const MOCK_CONTRACTOR_PROFILE: ContractorProfile = {
  companyName: "BuildRight Nigeria Ltd",
  rcNumber: "RC-1894220",
  contactName: "Emeka Okafor",
  phone: "08031234567",
  email: "projects@buildright.ng",
  location: "Abuja, FCT",
  bio: "Full-service construction company delivering residential and commercial builds across the FCT, with a focus on diaspora-funded projects.",
  specialties: ["Residential Builds", "Duplexes & Mansions", "Commercial"],
  teamSize: "16–30",
  yearsExperience: "10+ years",
  rating: 4.8,
  reviewCount: 19,
  completedProjects: 27,
  avatarUrl: null,
  verificationStatus: "verified",
  bankStatus: "verified",
  onboardingComplete: true,
  onboardingStep: 5,
  memberSince: "2023-04-12",
};

const TODO_MILESTONES = (projectId: string): ContractorMilestone[] => [
  {
    id: `${projectId}-m1`,
    stage: "foundation",
    label: "Foundation",
    amount: 4_500_000,
    status: "released",
    inspectorName: "Engr. Bala Yusuf",
    evidenceCount: 12,
  },
  {
    id: `${projectId}-m2`,
    stage: "structure",
    label: "Structure / Block Work",
    amount: 6_750_000,
    status: "released",
    inspectorName: "Engr. Bala Yusuf",
    evidenceCount: 18,
  },
  {
    id: `${projectId}-m3`,
    stage: "roofing",
    label: "Roofing",
    amount: 4_500_000,
    status: "under_review",
    inspectorName: "Engr. Bala Yusuf",
    evidenceCount: 9,
    dueDate: "2026-06-26",
    note: "Roof trusses and covering complete. Awaiting inspector sign-off.",
  },
  {
    id: `${projectId}-m4`,
    stage: "electrical_plumbing",
    label: "Electrical & Plumbing",
    amount: 3_750_000,
    status: "in_progress",
    dueDate: "2026-07-18",
  },
  {
    id: `${projectId}-m5`,
    stage: "finishing",
    label: "Finishing",
    amount: 3_750_000,
    status: "pending",
  },
  {
    id: `${projectId}-m6`,
    stage: "handover",
    label: "Handover",
    amount: 1_750_000,
    status: "pending",
  },
];

export const MOCK_CONTRACTOR_PROJECTS: ContractorProject[] = [
  {
    id: "cp-1",
    title: "Adeyemi 5-Bedroom Duplex",
    clientName: "Tunde Adeyemi",
    clientType: "diaspora",
    location: "Guzape, Abuja",
    contractValue: 25_000_000,
    status: "in_progress",
    progress: 62,
    imageUrl:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
    startedAt: "2026-01-15",
    deadline: "2026-09-30",
    currentStage: "roofing",
    milestones: TODO_MILESTONES("cp-1"),
    teamMemberIds: ["tm-1", "tm-2", "tm-3", "tm-6"],
    nextActionNote: "Submit roofing milestone evidence for inspector review.",
  },
  {
    id: "cp-2",
    title: "Grace Chapel Auditorium",
    clientName: "Grace Chapel Intl.",
    clientType: "religious",
    location: "Lugbe, Abuja",
    contractValue: 48_000_000,
    status: "in_progress",
    progress: 28,
    imageUrl:
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80",
    startedAt: "2026-03-02",
    deadline: "2027-02-28",
    currentStage: "structure",
    milestones: [
      {
        id: "cp-2-m1",
        stage: "foundation",
        label: "Foundation",
        amount: 8_640_000,
        status: "released",
        inspectorName: "Engr. Halima Sani",
        evidenceCount: 15,
      },
      {
        id: "cp-2-m2",
        stage: "structure",
        label: "Structure / Columns",
        amount: 12_960_000,
        status: "in_progress",
        dueDate: "2026-08-10",
      },
      {
        id: "cp-2-m3",
        stage: "roofing",
        label: "Roofing",
        amount: 8_640_000,
        status: "pending",
      },
      {
        id: "cp-2-m4",
        stage: "electrical_plumbing",
        label: "Electrical & Plumbing",
        amount: 7_200_000,
        status: "pending",
      },
      {
        id: "cp-2-m5",
        stage: "finishing",
        label: "Finishing",
        amount: 7_200_000,
        status: "pending",
      },
      {
        id: "cp-2-m6",
        stage: "handover",
        label: "Handover",
        amount: 3_360_000,
        status: "pending",
      },
    ],
    teamMemberIds: ["tm-1", "tm-4", "tm-5", "tm-6"],
    nextActionNote: "Complete column casting to first-floor level.",
  },
  {
    id: "cp-3",
    title: "Okoye Bungalow Renovation",
    clientName: "Chidinma Okoye",
    clientType: "individual",
    location: "Kubwa, Abuja",
    contractValue: 9_500_000,
    status: "completed",
    progress: 100,
    imageUrl:
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80",
    startedAt: "2025-08-01",
    deadline: "2025-12-20",
    currentStage: "handover",
    milestones: [
      { id: "cp-3-m1", stage: "foundation", label: "Foundation Repair", amount: 1_500_000, status: "released" },
      { id: "cp-3-m2", stage: "structure", label: "Structure", amount: 2_500_000, status: "released" },
      { id: "cp-3-m3", stage: "roofing", label: "Roofing", amount: 1_800_000, status: "released" },
      { id: "cp-3-m4", stage: "electrical_plumbing", label: "Electrical & Plumbing", amount: 1_500_000, status: "released" },
      { id: "cp-3-m5", stage: "finishing", label: "Finishing", amount: 1_500_000, status: "released" },
      { id: "cp-3-m6", stage: "handover", label: "Handover", amount: 700_000, status: "released" },
    ],
    teamMemberIds: ["tm-2", "tm-3"],
  },
];

// Aggregate vault across active projects (PRD §8 — no wallet wording).
export const MOCK_CONTRACTOR_VAULT: ContractorVault = {
  contractValue: 73_000_000,
  protectedFunds: 38_200_000,
  releasedFunds: 32_490_000,
  pendingMilestoneAmount: 4_500_000,
};

export const MOCK_MARKETPLACE_PROJECTS: MarketplaceProject[] = [
  {
    id: "mp-1",
    name: "Eze 4-Bedroom Terrace (3 units)",
    location: "Karsana, Abuja",
    budget: 42_000_000,
    timelineWeeks: 48,
    clientType: "diaspora",
    designDocsAvailable: true,
    imageUrl:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    postedAt: "2026-06-18T09:00:00Z",
    bidStatus: "open",
    buildingType: "Terrace (3 units)",
    description:
      "Diaspora client building a 3-unit terrace for rental income. Architectural drawings and BOQ are ready. Looking for a verified contractor to start Q3.",
    scope: [
      "Site clearing & setting out",
      "Foundation & DPC",
      "Block work to roof level",
      "Roofing (stone-coated)",
      "M&E first & second fix",
      "Finishing & external works",
    ],
  },
  {
    id: "mp-2",
    name: "Okonkwo Family Mansion",
    location: "Asokoro, Abuja",
    budget: 120_000_000,
    timelineWeeks: 72,
    clientType: "diaspora",
    designDocsAvailable: true,
    imageUrl:
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80",
    postedAt: "2026-06-15T14:00:00Z",
    bidStatus: "saved",
    buildingType: "Detached mansion",
    description:
      "Luxury 6-bedroom mansion with BQ, pool, and smart-home pre-wiring. Full design package available. Independent inspection on each milestone.",
    scope: [
      "Substructure & basement",
      "Superstructure",
      "Roofing & waterproofing",
      "M&E + smart home pre-wiring",
      "High-end finishing",
      "External works & landscaping",
    ],
  },
  {
    id: "mp-3",
    name: "Community Health Centre",
    location: "Bwari, Abuja",
    budget: 35_000_000,
    timelineWeeks: 40,
    clientType: "community",
    designDocsAvailable: false,
    imageUrl:
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80",
    postedAt: "2026-06-10T08:00:00Z",
    bidStatus: "submitted",
    buildingType: "Single-storey clinic",
    description:
      "Community-funded primary health centre. Contractor to advise on drawings as part of the bid. Phased release tied to inspection.",
    scope: [
      "Design support & approvals",
      "Foundation",
      "Structure & roofing",
      "M&E",
      "Finishing & fittings",
    ],
  },
  {
    id: "mp-4",
    name: "Adebayo Plaza (Shops + Offices)",
    location: "Wuse 2, Abuja",
    budget: 88_000_000,
    timelineWeeks: 60,
    clientType: "company",
    designDocsAvailable: true,
    imageUrl:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    postedAt: "2026-06-05T11:30:00Z",
    bidStatus: "open",
    buildingType: "Mixed-use plaza",
    description:
      "Commercial plaza with ground-floor retail and two floors of offices. Drawings and structural design complete.",
    scope: [
      "Piling & foundation",
      "Frame structure (3 floors)",
      "Roofing & cladding",
      "M&E + lift shaft",
      "Finishing & shopfronts",
    ],
  },
];

export const MOCK_MARKETPLACE_ARTISANS: MarketplaceArtisan[] = [
  {
    id: "ar-1",
    name: "Sunday Effiong",
    field: "mason",
    skills: ["Block work", "Plastering", "Screeding", "Setting out"],
    location: "Lugbe, Abuja",
    bio: "Master mason with a sharp eye for level work. Has set out and built shells for diaspora duplexes and a church auditorium across the FCT.",
    avatarUrl: null,
    verified: true,
    rating: 4.9,
    reviewCount: 23,
    completedProjects: 31,
    yearsExperience: 12,
    dayRate: 12_000,
    availability: "available",
    saved: false,
    history: [
      { title: "Adeyemi 5-Bedroom Duplex", role: "Lead mason — block work to roof level", year: "2026", location: "Guzape, Abuja" },
      { title: "Grace Chapel Auditorium", role: "Block work & plastering", year: "2026", location: "Lugbe, Abuja" },
      { title: "Bello Twin Bungalows", role: "Setting out & foundation", year: "2025", location: "Kuje, Abuja" },
    ],
  },
  {
    id: "ar-2",
    name: "Musa Danladi",
    field: "electrician",
    skills: ["First & second fix", "Distribution boards", "Solar/inverter", "Smart-home pre-wiring"],
    location: "Wuse, Abuja",
    bio: "Certified electrician handling everything from conduit runs to inverter and smart-home pre-wiring. COREN-supervised installations.",
    avatarUrl: null,
    verified: true,
    rating: 4.8,
    reviewCount: 18,
    completedProjects: 26,
    yearsExperience: 9,
    dayRate: 15_000,
    availability: "limited",
    saved: true,
    history: [
      { title: "Okonkwo Family Mansion", role: "M&E first fix + smart-home pre-wiring", year: "2026", location: "Asokoro, Abuja" },
      { title: "Adebayo Plaza", role: "Distribution boards & lift-shaft power", year: "2025", location: "Wuse 2, Abuja" },
    ],
  },
  {
    id: "ar-3",
    name: "Ifeanyi Nwosu",
    field: "carpenter",
    skills: ["Roof carpentry", "Formwork", "Doors & frames", "Built-in furniture"],
    location: "Kubwa, Abuja",
    bio: "Finish carpenter and formwork specialist. Builds roof structures, fits doors, and crafts built-in wardrobes and kitchens.",
    avatarUrl: null,
    verified: true,
    rating: 4.7,
    reviewCount: 15,
    completedProjects: 22,
    yearsExperience: 8,
    dayRate: 13_000,
    availability: "available",
    saved: false,
    history: [
      { title: "Adeyemi 5-Bedroom Duplex", role: "Roof carpentry & door fitting", year: "2026", location: "Guzape, Abuja" },
      { title: "Okoye Bungalow Renovation", role: "Built-in wardrobes & kitchen", year: "2025", location: "Kubwa, Abuja" },
    ],
  },
  {
    id: "ar-4",
    name: "Patrick Obi",
    field: "plumber",
    skills: ["Soil & waste", "Pressurised supply", "Borehole connection", "Sanitary fittings"],
    location: "Lokogoma, Abuja",
    bio: "Plumbing contractor for residential and commercial builds. Handles concealed pipework, water treatment tie-ins, and sanitary fit-out.",
    avatarUrl: null,
    verified: false,
    rating: 4.6,
    reviewCount: 11,
    completedProjects: 17,
    yearsExperience: 7,
    dayRate: 12_500,
    availability: "available",
    saved: false,
    history: [
      { title: "Grace Chapel Auditorium", role: "Soil, waste & sanitary fittings", year: "2026", location: "Lugbe, Abuja" },
      { title: "Community Health Centre", role: "Pressurised supply & borehole tie-in", year: "2025", location: "Bwari, Abuja" },
    ],
  },
  {
    id: "ar-5",
    name: "Hauwa Ibrahim",
    field: "tiler",
    skills: ["Floor & wall tiling", "Granite & marble", "Waterproofing", "Mosaic"],
    location: "Gwarinpa, Abuja",
    bio: "Precision tiler known for clean grout lines and large-format granite. Handles wet-area waterproofing before laying.",
    avatarUrl: null,
    verified: true,
    rating: 4.9,
    reviewCount: 20,
    completedProjects: 28,
    yearsExperience: 10,
    dayRate: 14_000,
    availability: "limited",
    saved: false,
    history: [
      { title: "Okonkwo Family Mansion", role: "Granite floors & bathroom waterproofing", year: "2026", location: "Asokoro, Abuja" },
      { title: "Adebayo Plaza", role: "Retail floor tiling", year: "2025", location: "Wuse 2, Abuja" },
    ],
  },
  {
    id: "ar-6",
    name: "Tope Bamigboye",
    field: "welder",
    skills: ["Gates & railings", "Structural steel", "Aluminium-steel composite", "Burglary proofs"],
    location: "Karu, Abuja",
    bio: "Metal fabricator producing gates, balustrades and structural steel. Mobile workshop for on-site fit-up and welding.",
    avatarUrl: null,
    verified: true,
    rating: 4.7,
    reviewCount: 14,
    completedProjects: 19,
    yearsExperience: 11,
    dayRate: 16_000,
    availability: "engaged",
    saved: false,
    history: [
      { title: "Okonkwo Family Mansion", role: "Balustrades, gates & burglary proofs", year: "2026", location: "Asokoro, Abuja" },
      { title: "Adebayo Plaza", role: "Structural steel for canopy", year: "2025", location: "Wuse 2, Abuja" },
    ],
  },
  {
    id: "ar-7",
    name: "Blessing Adeniyi",
    field: "pop_ceiling",
    skills: ["POP ceilings", "Cornices", "Screeding", "Decorative mouldings"],
    location: "Lifecamp, Abuja",
    bio: "POP and decorative ceiling finisher. Designs and installs coffered ceilings, cornices and feature walls.",
    avatarUrl: null,
    verified: false,
    rating: 4.5,
    reviewCount: 9,
    completedProjects: 13,
    yearsExperience: 6,
    dayRate: 11_000,
    availability: "available",
    saved: false,
    history: [
      { title: "Okonkwo Family Mansion", role: "Coffered ceilings & cornices", year: "2026", location: "Asokoro, Abuja" },
      { title: "Okoye Bungalow Renovation", role: "POP ceiling & feature wall", year: "2025", location: "Kubwa, Abuja" },
    ],
  },
  {
    id: "ar-8",
    name: "Yakubu Sani",
    field: "steel_fixer",
    skills: ["Rebar bending", "Column & beam cages", "Slab reinforcement", "BOQ take-off"],
    location: "Mararaba, Abuja",
    bio: "Iron bender and steel fixer for substructure and frame work. Reads structural drawings and ties cages to spec.",
    avatarUrl: null,
    verified: true,
    rating: 4.8,
    reviewCount: 16,
    completedProjects: 24,
    yearsExperience: 13,
    dayRate: 13_500,
    availability: "available",
    saved: false,
    history: [
      { title: "Grace Chapel Auditorium", role: "Column & beam reinforcement", year: "2026", location: "Lugbe, Abuja" },
      { title: "Adebayo Plaza", role: "Slab & frame steel fixing", year: "2025", location: "Wuse 2, Abuja" },
    ],
  },
];

export const MOCK_CONTRACTOR_BIDS: ContractorBid[] = [
  {
    id: "bid-1",
    projectId: "mp-3",
    projectName: "Community Health Centre",
    clientName: "Bwari Community Trust",
    materialCost: 18_000_000,
    laborCost: 9_500_000,
    equipmentCost: 3_500_000,
    contractorFee: 4_000_000,
    total: 35_000_000,
    timelineWeeks: 40,
    teamMemberIds: ["tm-1", "tm-5"],
    notes: "Includes design support and BOQ preparation in week 1–2.",
    submittedAt: "2026-06-12T10:00:00Z",
    status: "submitted",
  },
  {
    id: "bid-2",
    projectId: "cp-1",
    projectName: "Adeyemi 5-Bedroom Duplex",
    clientName: "Tunde Adeyemi",
    materialCost: 13_000_000,
    laborCost: 6_500_000,
    equipmentCost: 2_500_000,
    contractorFee: 3_000_000,
    total: 25_000_000,
    timelineWeeks: 36,
    teamMemberIds: ["tm-1", "tm-2", "tm-3"],
    notes: "Phased to align with diaspora funding schedule.",
    submittedAt: "2025-12-20T09:00:00Z",
    status: "accepted",
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "tm-1",
    name: "Engr. Bala Yusuf",
    role: "engineer",
    phone: "08020000001",
    permissions: ["upload_proof", "update_progress", "view_financials"],
    assignedProjectId: "cp-1",
    status: "active",
  },
  {
    id: "tm-2",
    name: "Sunday Effiong",
    role: "mason",
    phone: "08020000002",
    permissions: ["upload_proof", "update_progress"],
    assignedProjectId: "cp-1",
    status: "active",
  },
  {
    id: "tm-3",
    name: "Ifeanyi Nwosu",
    role: "carpenter",
    phone: "08020000003",
    permissions: ["upload_proof"],
    assignedProjectId: "cp-1",
    status: "active",
  },
  {
    id: "tm-4",
    name: "Musa Danladi",
    role: "electrician",
    phone: "08020000004",
    permissions: ["upload_proof", "update_progress"],
    assignedProjectId: "cp-2",
    status: "active",
  },
  {
    id: "tm-5",
    name: "Patrick Obi",
    role: "plumber",
    phone: "08020000005",
    permissions: ["upload_proof"],
    assignedProjectId: "cp-2",
    status: "invited",
  },
  {
    id: "tm-6",
    name: "Grace Aliyu",
    role: "supervisor",
    phone: "08020000006",
    permissions: ["upload_proof", "update_progress", "view_financials"],
    assignedProjectId: "cp-1",
    status: "active",
  },
];

export const MOCK_CONTRACTOR_DOCUMENTS: ContractorDocument[] = [
  { id: "doc-1", name: "Foundation pour — site photos", kind: "photo", projectName: "Adeyemi Duplex", uploadedAt: "2026-02-10T09:00:00Z", sizeLabel: "8 photos" },
  { id: "doc-2", name: "Cement & rod receipts (Jan)", kind: "receipt", projectName: "Adeyemi Duplex", uploadedAt: "2026-02-02T09:00:00Z", sizeLabel: "1.2 MB" },
  { id: "doc-3", name: "Bill of Quantities", kind: "boq", projectName: "Grace Chapel Auditorium", uploadedAt: "2026-03-01T09:00:00Z", sizeLabel: "640 KB" },
  { id: "doc-4", name: "Structural drawings (rev B)", kind: "drawing", projectName: "Grace Chapel Auditorium", uploadedAt: "2026-03-01T09:00:00Z", sizeLabel: "4.8 MB" },
  { id: "doc-5", name: "Roofing progress walkthrough", kind: "video", projectName: "Adeyemi Duplex", uploadedAt: "2026-06-20T09:00:00Z", sizeLabel: "00:48" },
  { id: "doc-6", name: "Weekly site report — Wk 21", kind: "report", projectName: "Adeyemi Duplex", uploadedAt: "2026-06-19T09:00:00Z", sizeLabel: "320 KB" },
  { id: "doc-7", name: "Handover certificate", kind: "completion", projectName: "Okoye Bungalow Renovation", uploadedAt: "2025-12-20T09:00:00Z", sizeLabel: "210 KB" },
];

export const MOCK_CONTRACTOR_UPDATES: ContractorUpdate[] = [
  {
    id: "up-1",
    projectName: "Adeyemi 5-Bedroom Duplex",
    authorName: "Grace Aliyu",
    authorRole: "Supervisor",
    text: "Roof covering completed. Uploaded 9 photos for inspector review.",
    createdAt: "2026-06-20T16:00:00Z",
    tone: "success",
    photoCount: 9,
  },
  {
    id: "up-2",
    projectName: "Grace Chapel Auditorium",
    authorName: "Musa Danladi",
    authorRole: "Electrician",
    text: "First-fix conduit runs started on ground floor.",
    createdAt: "2026-06-19T11:30:00Z",
    tone: "info",
    photoCount: 4,
  },
  {
    id: "up-3",
    projectName: "Adeyemi 5-Bedroom Duplex",
    authorName: "Engr. Bala Yusuf",
    authorRole: "Engineer",
    text: "Structure milestone funds released by client. Moving to roofing.",
    createdAt: "2026-06-12T09:00:00Z",
    tone: "success",
  },
  {
    id: "up-4",
    projectName: "Grace Chapel Auditorium",
    authorName: "Sunday Effiong",
    authorRole: "Mason",
    text: "Column reinforcement tied to first-floor level.",
    createdAt: "2026-06-11T15:00:00Z",
    tone: "neutral",
    photoCount: 6,
  },
];

export const MOCK_CONTRACTOR_NOTIFICATIONS: ContractorNotification[] = [
  {
    id: "n-1",
    type: "info",
    title: "New project on the marketplace",
    body: "A diaspora client posted a 3-unit terrace in Karsana — design docs available.",
    read: false,
    createdAt: "2026-06-18T09:00:00Z",
    actionLabel: "View project",
    actionView: "marketplace",
  },
  {
    id: "n-2",
    type: "warning",
    title: "Milestone awaiting inspection",
    body: "Roofing on Adeyemi Duplex is under review. Inspector sign-off unlocks release.",
    read: false,
    createdAt: "2026-06-20T16:30:00Z",
    actionLabel: "Open vault",
    actionView: "vault",
  },
  {
    id: "n-3",
    type: "success",
    title: "Structure milestone released",
    body: "₦6,750,000 released to your payout account for Adeyemi Duplex.",
    read: true,
    createdAt: "2026-06-12T09:05:00Z",
  },
];

export const MOCK_CONTRACTOR_REVIEWS: ContractorReview[] = [
  {
    id: "rv-1",
    clientName: "Chidinma Okoye",
    projectTitle: "Okoye Bungalow Renovation",
    rating: 5,
    comment: "Finished ahead of schedule and the milestone releases kept everything transparent. Highly recommend.",
    createdAt: "2025-12-22T09:00:00Z",
  },
  {
    id: "rv-2",
    clientName: "Tunde Adeyemi",
    projectTitle: "Adeyemi 5-Bedroom Duplex",
    rating: 5,
    comment: "As a diaspora client I could see every stage and the protected funds. Excellent communication.",
    createdAt: "2026-06-13T09:00:00Z",
  },
  {
    id: "rv-3",
    clientName: "Bello Estates",
    projectTitle: "Bello Twin Bungalows",
    rating: 4,
    comment: "Solid build quality. Minor delay during rains but kept us updated throughout.",
    createdAt: "2025-09-30T09:00:00Z",
  },
];
