/**
 * Demo fixtures for the architect portal.
 *
 * Dates are generated relative to "today" so the dashboard always demonstrates a
 * live workload: something overdue, something due tomorrow, a client who has gone
 * quiet, an unsigned agreement and a proposal closing today.
 *
 * The set deliberately includes the awkward states as well as the happy path —
 * a blocked project, a disputed milestone, an off-platform client, an expired
 * proposal, a locked deliverable and a project whose included revisions are spent.
 */

import { DESIGN_ONLY_EXCLUSIONS } from "./constants";
import { isoInDays } from "./utils";
import type {
  ArchitectActivity,
  ArchitectNotification,
  ArchitectProfile,
  ArchitectProject,
  ArchitectProposal,
  ClientBrief,
  ConversationSummary,
  DesignOpportunity,
  PortfolioItem,
  ProjectMessage,
  TeamMember,
} from "./types";

const IMG = {
  duplex: "/assets/duplex.PNG",
  duplexSuplex: "/assets/duplex-suplex.jpeg",
  bungalow: "/assets/bungalow.PNG",
  villa: "/assets/lifestyle/villa.jpg",
  apartments: "/assets/lifestyle/apartments.jpg",
  investment: "/assets/investment-property.PNG",
  multiFamily: "/assets/multi-family.PNG",
  afroModern: "/assets/ambience/afro-modern.jpeg",
  luxury: "/assets/ambience/luxury-contemporary.jpeg",
  minimalist: "/assets/ambience/modern-minimalist.jpeg",
  classical: "/assets/ambience/classical.jpeg",
  neoclassic: "/assets/ambience/neoclassic.jpeg",
};

/* ------------------------------------------------------------------ *
 * Profile
 * ------------------------------------------------------------------ */

export const MOCK_ARCHITECT_PROFILE: ArchitectProfile = {
  studioName: "Okumagba Design Studio",
  contactName: "Chidi Okumagba",
  phone: "08031234567",
  email: "studio@okumagba.design",
  location: "Abuja, Nigeria",
  bio: "Residential and commercial architecture with a focus on diaspora-led builds.",
  specialties: ["Residential", "Duplex", "Modern Tropical"],
  licenseNumber: "ARCON-2019-4421",
  rating: 4.9,
  reviewCount: 28,
  avatarUrl: null,
  verificationStatus: "verified",
  bankStatus: "verified",
  onboardingComplete: true,
  onboardingStep: 5,
  subscriptionPlan: "pro",
  subscriptionRenewal: isoInDays(49),
};

/* ------------------------------------------------------------------ *
 * Client briefs (Build Your Dream Home submissions)
 * ------------------------------------------------------------------ */

const idemetoBrief: ClientBrief = {
  id: "brief-idemeto",
  submittedAt: isoInDays(-96),
  projectType: "Family home",
  siteLocation: "Independence Layout, Enugu",
  clientLocation: "Houston, United States",
  bedrooms: 5,
  floors: 2,
  requiredSpaces: [
    "Family lounge",
    "Formal sitting room",
    "Open-plan kitchen",
    "Home office",
    "Guest suite",
    "Boys' quarters",
    "Covered outdoor dining",
  ],
  preferredStyle: "Afro Modern",
  budgetRange: "₦150M – ₦300M",
  inspirationImages: [IMG.afroModern, IMG.luxury, IMG.minimalist],
  desiredTimeline: "Design complete within 14 weeks",
  specialRequests:
    "Must accommodate a large extended family at Christmas. Prefer natural cross-ventilation over heavy air-conditioning.",
  surveyPlan: {
    id: "doc-idm-survey",
    name: "Survey plan — Plot 42 Independence Layout.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-95),
  },
  documents: [
    {
      id: "doc-idm-cofo",
      name: "Certificate of Occupancy.pdf",
      kind: "land_document",
      uploadedAt: isoInDays(-95),
    },
    {
      id: "doc-idm-site",
      name: "Site photographs (12).zip",
      kind: "photo",
      uploadedAt: isoInDays(-94),
    },
  ],
  localRepresentative: "Chinedu Idemeto (brother, Enugu)",
  clientVerified: true,
};

const adeniyiBrief: ClientBrief = {
  id: "brief-adeniyi",
  submittedAt: isoInDays(-71),
  projectType: "Family home",
  siteLocation: "Katampe Extension, Abuja",
  clientLocation: "Abuja, Nigeria",
  bedrooms: 4,
  floors: 2,
  requiredSpaces: [
    "Living area",
    "Kitchen with pantry",
    "Study",
    "Gym",
    "Two-car garage",
  ],
  preferredStyle: "Modern Minimalist",
  budgetRange: "₦50M – ₦150M",
  inspirationImages: [IMG.minimalist, IMG.duplexSuplex],
  desiredTimeline: "Drawings ready before the rainy season",
  specialRequests: "Solar-ready roof and provision for a borehole plant room.",
  surveyPlan: {
    id: "doc-ade-survey",
    name: "Survey plan — Katampe Ext.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-70),
  },
  documents: [],
  localRepresentative: null,
  clientVerified: true,
};

const riverViewBrief: ClientBrief = {
  id: "brief-riverview",
  submittedAt: isoInDays(-120),
  projectType: "Apartments",
  siteLocation: "Jabi Waterfront, Abuja",
  clientLocation: "London, United Kingdom",
  bedrooms: 3,
  floors: 4,
  requiredSpaces: [
    "12 × 3-bedroom units",
    "Shared lobby",
    "Rooftop terrace",
    "Basement parking",
    "Generator house",
  ],
  preferredStyle: "Contemporary Luxury",
  budgetRange: "₦300M+",
  inspirationImages: [IMG.apartments, IMG.luxury],
  desiredTimeline: "Full drawing set in 18 weeks",
  specialRequests: "Units must be rentable individually with separate metering.",
  surveyPlan: {
    id: "doc-rv-survey",
    name: "Survey plan — Jabi Waterfront.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-119),
  },
  documents: [
    {
      id: "doc-rv-geo",
      name: "Geotechnical report.pdf",
      kind: "land_document",
      uploadedAt: isoInDays(-118),
    },
  ],
  localRepresentative: "Bola Ade (site manager)",
  clientVerified: true,
};

const gwarinpaBrief: ClientBrief = {
  id: "brief-gwarinpa",
  submittedAt: isoInDays(-24),
  projectType: "Family home",
  siteLocation: "Gwarinpa 3rd Avenue, Abuja",
  clientLocation: "Abuja, Nigeria",
  bedrooms: 4,
  floors: 2,
  requiredSpaces: ["Living area", "Kitchen", "Family lounge", "Guest room", "BQ"],
  preferredStyle: "Neo Classical",
  budgetRange: "₦50M – ₦150M",
  inspirationImages: [IMG.neoclassic, IMG.duplex],
  desiredTimeline: "Design in 10 weeks",
  specialRequests: "Budget is fixed — no scope additions after the agreement.",
  surveyPlan: {
    id: "doc-gw-survey",
    name: "Survey plan — Gwarinpa.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-23),
  },
  documents: [],
  localRepresentative: null,
  clientVerified: true,
};

const kubwaBrief: ClientBrief = {
  id: "brief-kubwa",
  submittedAt: isoInDays(-58),
  projectType: "Investment property",
  siteLocation: "Kubwa Phase 2, Abuja",
  clientLocation: "Kaduna, Nigeria",
  bedrooms: 2,
  floors: 2,
  requiredSpaces: ["6 × 2-bedroom terrace units", "Shared compound", "Gatehouse"],
  preferredStyle: "Classical",
  budgetRange: "₦50M – ₦150M",
  inspirationImages: [IMG.classical],
  desiredTimeline: "Not fixed",
  specialRequests: "Client joined off-platform — brief captured by the studio.",
  surveyPlan: null,
  documents: [],
  localRepresentative: null,
  clientVerified: false,
};

const maitamaBrief: ClientBrief = {
  id: "brief-maitama",
  submittedAt: isoInDays(-240),
  projectType: "Family home",
  siteLocation: "Maitama District, Abuja",
  clientLocation: "Abuja, Nigeria",
  bedrooms: 6,
  floors: 3,
  requiredSpaces: ["Cinema room", "Pool deck", "Chef's kitchen", "Staff quarters"],
  preferredStyle: "Contemporary Luxury",
  budgetRange: "₦300M+",
  inspirationImages: [IMG.villa, IMG.luxury],
  desiredTimeline: "Completed",
  specialRequests: "—",
  surveyPlan: {
    id: "doc-mt-survey",
    name: "Survey plan — Maitama.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-239),
  },
  documents: [],
  localRepresentative: null,
  clientVerified: true,
};

/* ------------------------------------------------------------------ *
 * Projects
 * ------------------------------------------------------------------ */

export const MOCK_ARCHITECT_PROJECTS: ArchitectProject[] = [
  /* 1 — Client comments received on concept design. Revisions are also
     exhausted here, so the studio must price the next round. */
  {
    id: "ap-idemeto",
    title: "Idemeto Family Residence",
    clientName: "Ema Umoh",
    clientCompany: "Idemeto Family",
    clientVerified: true,
    location: "Enugu, Nigeria",
    imageUrl: IMG.afroModern,
    origin: "marketplace",
    appointment: "design_only",
    phase: "concept_revision",
    status: "revision_requested",
    nextAction: "Upload revised floor plans",
    responsibleParty: "architect",
    dueDate: isoInDays(1),
    paymentStatus: "funded",
    designFee: 7_500_000,
    startedAt: isoInDays(-88),
    lastUpdated: isoInDays(-1),
    includedRevisions: 2,
    revisionRoundsUsed: 2,
    clientReviewPeriodDays: 5,
    finalDecisionMaker: "Ema Umoh",
    brief: idemetoBrief,
    agreement: {
      id: "agr-idemeto",
      appointment: "design_only",
      status: "signed",
      totalDesignFee: 7_500_000,
      includedRevisions: 2,
      designTimelineWeeks: 14,
      clientReviewPeriodDays: 5,
      finalDecisionMaker: "Ema Umoh",
      deliverables: [
        "Concept design",
        "Floor plans",
        "Elevations & sections",
        "3D exterior renders",
        "Construction drawings",
      ],
      exclusions: [...DESIGN_ONLY_EXCLUSIONS],
      differences: [],
      confirmedSteps: [
        "summary",
        "scope",
        "differences",
        "deliverables",
        "revisions",
        "fees",
        "timeline",
        "authority",
        "exclusions",
        "sign",
      ],
      preparedFromProposalId: "prop-idemeto",
      signedAt: isoInDays(-84),
    },
    deliverables: [
      {
        id: "del-idm-1",
        name: "Project brief confirmation",
        phase: "brief_review",
        status: "complete",
        dueDate: isoInDays(-80),
        revisionRound: null,
        clientStatus: "approved",
        files: [
          {
            id: "f-idm-1",
            name: "Brief confirmation.pdf",
            format: "PDF",
            sizeLabel: "410 KB",
            uploadedAt: isoInDays(-81),
          },
        ],
        submittedAt: isoInDays(-81),
        approvedAt: isoInDays(-80),
      },
      {
        id: "del-idm-2",
        name: "Concept floor plans",
        phase: "concept_revision",
        status: "revision_requested",
        dueDate: isoInDays(1),
        revisionRound: 2,
        clientStatus: "revision_requested",
        files: [
          {
            id: "f-idm-2",
            name: "Concept floor plans r1.pdf",
            format: "PDF",
            sizeLabel: "6.2 MB",
            uploadedAt: isoInDays(-12),
          },
        ],
        submittedAt: isoInDays(-12),
      },
      {
        id: "del-idm-3",
        name: "Exterior renders",
        phase: "concept_design",
        status: "awaiting_client_review",
        dueDate: isoInDays(-2),
        revisionRound: 1,
        clientStatus: "pending",
        files: [
          {
            id: "f-idm-3",
            name: "Exterior renders.zip",
            format: "ZIP",
            sizeLabel: "48 MB",
            uploadedAt: isoInDays(-4),
          },
        ],
        submittedAt: isoInDays(-4),
      },
      {
        id: "del-idm-4",
        name: "Developed design set",
        phase: "developed_design",
        status: "locked",
        dueDate: null,
        revisionRound: null,
        clientStatus: "not_applicable",
        lockedReason: "Requires concept approval",
        files: [],
      },
    ],
    approvals: [
      {
        id: "app-idm-1",
        stage: "project_brief",
        status: "approved",
        submittedAt: isoInDays(-82),
        decidedAt: isoInDays(-80),
        decidedBy: "Ema Umoh",
      },
      {
        id: "app-idm-2",
        stage: "concept_design",
        status: "revision_requested",
        submittedAt: isoInDays(-12),
        dueDate: isoInDays(-7),
        decidedAt: isoInDays(-2),
        decidedBy: "Ema Umoh",
        note: "Second round of comments returned.",
      },
      { id: "app-idm-3", stage: "developed_design", status: "not_submitted" },
      { id: "app-idm-4", stage: "final_drawings", status: "not_submitted" },
    ],
    revisions: [
      {
        id: "rev-idm-2",
        deliverableId: "del-idm-2",
        deliverableName: "Concept floor plans",
        round: 2,
        submittedAt: isoInDays(-2),
        responseDeadline: isoInDays(1),
        status: "open",
        comments: [
          {
            id: "cmt-idm-1",
            text: "The kitchen feels tight when the whole family is around.",
            requestedChange: "Widen the kitchen island run by about a metre.",
            submittedBy: "Ema Umoh",
            submittedByRole: "decision_maker",
            submittedAt: isoInDays(-2),
            binding: true,
          },
          {
            id: "cmt-idm-2",
            text: "Could we add a second staircase at the rear?",
            requestedChange: "Add a rear service staircase.",
            submittedBy: "Nkechi Idemeto",
            submittedByRole: "family_member",
            submittedAt: isoInDays(-2),
            binding: false,
          },
          {
            id: "cmt-idm-3",
            text: "The guest suite window looks straight at the neighbour.",
            requestedChange: "Reposition the guest suite window.",
            markupUrl: "/assets/ambience/afro-modern.jpeg",
            submittedBy: "Ema Umoh",
            submittedByRole: "decision_maker",
            submittedAt: isoInDays(-1),
            binding: true,
          },
        ],
      },
    ],
    payments: [
      {
        id: "pm-idm-1",
        name: "Brief confirmation",
        amount: 1_125_000,
        status: "paid",
        fundedAt: isoInDays(-86),
        earnedAt: isoInDays(-80),
        paidAt: isoInDays(-76),
      },
      {
        id: "pm-idm-2",
        name: "Concept presentation",
        amount: 1_875_000,
        status: "funded",
        dueDate: isoInDays(1),
        fundedAt: isoInDays(-30),
      },
      { id: "pm-idm-3", name: "Developed design", amount: 2_250_000, status: "not_funded" },
      { id: "pm-idm-4", name: "Construction drawings", amount: 2_250_000, status: "not_funded" },
    ],
    documents: [
      {
        id: "pdoc-idm-1",
        name: "Signed agreement — Idemeto.pdf",
        format: "PDF",
        category: "agreement",
        uploadedAt: isoInDays(-84),
        uploadedBy: "Amana",
      },
      {
        id: "pdoc-idm-2",
        name: "Survey plan — Plot 42.pdf",
        format: "PDF",
        category: "survey",
        uploadedAt: isoInDays(-95),
        uploadedBy: "Ema Umoh",
      },
    ],
    conversationSummaries: [
      {
        id: "cs-idm-1",
        projectId: "ap-idemeto",
        date: isoInDays(-5),
        participants: "Chidi Okumagba, Ema Umoh",
        discussion: "Reviewed the concept over a video call and walked through the plan layout.",
        decision: "Kitchen to be widened; rear staircase to be priced separately.",
        requiredAction: "Issue revised plans and a quote for the staircase.",
        status: "confirmed",
        createdAt: isoInDays(-5),
      },
    ],
  },

  /* 2 — Developed design is due tomorrow. */
  {
    id: "ap-adeniyi",
    title: "Adeniyi Residence",
    clientName: "Tunde Adeniyi",
    clientVerified: true,
    location: "Katampe Extension, Abuja",
    imageUrl: IMG.minimalist,
    origin: "marketplace",
    appointment: "design_only",
    phase: "developed_design",
    status: "deliverable_due",
    nextAction: "Upload the developed design set",
    responsibleParty: "architect",
    dueDate: isoInDays(1),
    paymentStatus: "funded",
    designFee: 4_800_000,
    startedAt: isoInDays(-64),
    lastUpdated: isoInDays(-2),
    includedRevisions: 2,
    revisionRoundsUsed: 1,
    clientReviewPeriodDays: 5,
    finalDecisionMaker: "Tunde Adeniyi",
    brief: adeniyiBrief,
    agreement: {
      id: "agr-adeniyi",
      appointment: "design_only",
      status: "signed",
      totalDesignFee: 4_800_000,
      includedRevisions: 2,
      designTimelineWeeks: 12,
      clientReviewPeriodDays: 5,
      finalDecisionMaker: "Tunde Adeniyi",
      deliverables: [
        "Concept design",
        "Floor plans",
        "Elevations & sections",
        "3D exterior renders",
        "Construction drawings",
      ],
      exclusions: [...DESIGN_ONLY_EXCLUSIONS],
      differences: [],
      confirmedSteps: [
        "summary",
        "scope",
        "differences",
        "deliverables",
        "revisions",
        "fees",
        "timeline",
        "authority",
        "exclusions",
        "sign",
      ],
      preparedFromProposalId: "prop-adeniyi",
      signedAt: isoInDays(-60),
    },
    deliverables: [
      {
        id: "del-ade-1",
        name: "Project brief confirmation",
        phase: "brief_review",
        status: "complete",
        dueDate: isoInDays(-56),
        revisionRound: null,
        clientStatus: "approved",
        files: [],
        submittedAt: isoInDays(-58),
        approvedAt: isoInDays(-56),
      },
      {
        id: "del-ade-2",
        name: "Concept design pack",
        phase: "concept_approved",
        status: "approved",
        dueDate: isoInDays(-20),
        revisionRound: 1,
        clientStatus: "approved_with_comments",
        files: [
          {
            id: "f-ade-1",
            name: "Concept pack r2.pdf",
            format: "PDF",
            sizeLabel: "8.4 MB",
            uploadedAt: isoInDays(-22),
          },
        ],
        submittedAt: isoInDays(-22),
        approvedAt: isoInDays(-18),
      },
      {
        id: "del-ade-3",
        name: "Developed design set",
        phase: "developed_design",
        status: "in_progress",
        dueDate: isoInDays(1),
        revisionRound: null,
        clientStatus: "not_submitted",
        files: [],
      },
      {
        id: "del-ade-4",
        name: "Construction drawings",
        phase: "construction_drawings",
        status: "locked",
        dueDate: null,
        revisionRound: null,
        clientStatus: "not_applicable",
        lockedReason: "Requires developed-design approval",
        files: [],
      },
    ],
    approvals: [
      {
        id: "app-ade-1",
        stage: "project_brief",
        status: "approved",
        submittedAt: isoInDays(-58),
        decidedAt: isoInDays(-56),
        decidedBy: "Tunde Adeniyi",
      },
      {
        id: "app-ade-2",
        stage: "concept_design",
        status: "approved_with_comments",
        submittedAt: isoInDays(-22),
        decidedAt: isoInDays(-18),
        decidedBy: "Tunde Adeniyi",
        note: "Approved subject to the gym being moved to the ground floor.",
      },
      { id: "app-ade-3", stage: "developed_design", status: "not_submitted" },
      { id: "app-ade-4", stage: "final_drawings", status: "not_submitted" },
    ],
    revisions: [],
    payments: [
      {
        id: "pm-ade-1",
        name: "Brief confirmation",
        amount: 720_000,
        status: "paid",
        fundedAt: isoInDays(-62),
        earnedAt: isoInDays(-56),
        paidAt: isoInDays(-52),
      },
      {
        id: "pm-ade-2",
        name: "Concept presentation",
        amount: 1_200_000,
        status: "available_for_withdrawal",
        earnedAt: isoInDays(-18),
      },
      {
        id: "pm-ade-3",
        name: "Developed design",
        amount: 1_440_000,
        status: "work_in_progress",
        dueDate: isoInDays(1),
        fundedAt: isoInDays(-18),
      },
      { id: "pm-ade-4", name: "Construction drawings", amount: 1_440_000, status: "not_funded" },
    ],
    documents: [
      {
        id: "pdoc-ade-1",
        name: "Signed agreement — Adeniyi.pdf",
        format: "PDF",
        category: "agreement",
        uploadedAt: isoInDays(-60),
        uploadedBy: "Amana",
      },
    ],
    conversationSummaries: [],
  },

  /* 3 — Client approval has been pending for five days. */
  {
    id: "ap-riverview",
    title: "River View Apartments",
    clientName: "Adaeze Nwankwo",
    clientCompany: "River View Ltd",
    clientVerified: true,
    location: "Jabi, Abuja",
    imageUrl: IMG.apartments,
    origin: "marketplace",
    appointment: "design_only",
    phase: "client_developed_review",
    status: "client_review_in_progress",
    nextAction: "Waiting for the client to approve the developed design",
    responsibleParty: "client",
    dueDate: isoInDays(-2),
    paymentStatus: "pending",
    designFee: 12_000_000,
    startedAt: isoInDays(-112),
    lastUpdated: isoInDays(-5),
    waitingOnClientSince: isoInDays(-5),
    includedRevisions: 3,
    revisionRoundsUsed: 1,
    clientReviewPeriodDays: 3,
    finalDecisionMaker: "Adaeze Nwankwo",
    brief: riverViewBrief,
    agreement: {
      id: "agr-riverview",
      appointment: "design_only",
      status: "signed",
      totalDesignFee: 12_000_000,
      includedRevisions: 3,
      designTimelineWeeks: 18,
      clientReviewPeriodDays: 3,
      finalDecisionMaker: "Adaeze Nwankwo",
      deliverables: [
        "Concept design",
        "Floor plans",
        "Elevations & sections",
        "3D exterior renders",
        "Construction drawings",
        "Planning-approval drawing set",
      ],
      exclusions: [...DESIGN_ONLY_EXCLUSIONS, "Structural engineering design"],
      differences: [],
      confirmedSteps: [
        "summary",
        "scope",
        "differences",
        "deliverables",
        "revisions",
        "fees",
        "timeline",
        "authority",
        "exclusions",
        "sign",
      ],
      preparedFromProposalId: null,
      signedAt: isoInDays(-108),
    },
    deliverables: [
      {
        id: "del-rv-1",
        name: "Concept design pack",
        phase: "concept_approved",
        status: "approved",
        dueDate: isoInDays(-60),
        revisionRound: 1,
        clientStatus: "approved",
        files: [],
        submittedAt: isoInDays(-64),
        approvedAt: isoInDays(-60),
      },
      {
        id: "del-rv-2",
        name: "Developed design set",
        phase: "client_developed_review",
        status: "awaiting_client_review",
        dueDate: isoInDays(-6),
        revisionRound: null,
        clientStatus: "pending",
        files: [
          {
            id: "f-rv-1",
            name: "Developed design set.zip",
            format: "ZIP",
            sizeLabel: "112 MB",
            uploadedAt: isoInDays(-5),
          },
        ],
        submittedAt: isoInDays(-5),
      },
      {
        id: "del-rv-3",
        name: "Construction drawings",
        phase: "construction_drawings",
        status: "locked",
        dueDate: null,
        revisionRound: null,
        clientStatus: "not_applicable",
        lockedReason: "Requires developed-design approval",
        files: [],
      },
    ],
    approvals: [
      {
        id: "app-rv-1",
        stage: "project_brief",
        status: "approved",
        submittedAt: isoInDays(-110),
        decidedAt: isoInDays(-108),
        decidedBy: "Adaeze Nwankwo",
      },
      {
        id: "app-rv-2",
        stage: "concept_design",
        status: "approved",
        submittedAt: isoInDays(-64),
        decidedAt: isoInDays(-60),
        decidedBy: "Adaeze Nwankwo",
      },
      {
        id: "app-rv-3",
        stage: "developed_design",
        status: "client_reviewing",
        submittedAt: isoInDays(-5),
        dueDate: isoInDays(-2),
      },
      { id: "app-rv-4", stage: "final_drawings", status: "not_submitted" },
    ],
    revisions: [],
    payments: [
      {
        id: "pm-rv-1",
        name: "Concept presentation",
        amount: 3_000_000,
        status: "paid",
        fundedAt: isoInDays(-100),
        earnedAt: isoInDays(-60),
        paidAt: isoInDays(-56),
      },
      {
        id: "pm-rv-2",
        name: "Developed design",
        amount: 3_600_000,
        status: "awaiting_approval",
        dueDate: isoInDays(-2),
        fundedAt: isoInDays(-58),
      },
      { id: "pm-rv-3", name: "Construction drawings", amount: 3_600_000, status: "not_funded" },
      { id: "pm-rv-4", name: "Final delivery", amount: 1_800_000, status: "not_funded" },
    ],
    documents: [
      {
        id: "pdoc-rv-1",
        name: "Geotechnical report.pdf",
        format: "PDF",
        category: "land",
        uploadedAt: isoInDays(-118),
        uploadedBy: "Adaeze Nwankwo",
      },
    ],
    conversationSummaries: [
      {
        id: "cs-rv-1",
        projectId: "ap-riverview",
        date: isoInDays(-9),
        participants: "Chidi Okumagba, Adaeze Nwankwo, Bola Ade",
        discussion: "Phone call about unit mix on the third floor.",
        decision: "Keep 12 units; convert the rooftop plant area into storage.",
        requiredAction: "Reflect the storage change in the developed design.",
        status: "pending",
        createdAt: isoInDays(-9),
      },
    ],
  },

  /* 4 — Selected, but the agreement is still unsigned and the brief and
     proposal disagree on two points. */
  {
    id: "ap-gwarinpa",
    title: "Gwarinpa Duplex",
    clientName: "Musa Bello",
    clientVerified: true,
    location: "Gwarinpa, Abuja",
    imageUrl: IMG.duplex,
    origin: "marketplace",
    appointment: "design_only",
    phase: "agreement_preparation",
    status: "awaiting_agreement",
    nextAction: "Confirm the agreement terms and sign",
    responsibleParty: "architect",
    dueDate: isoInDays(2),
    paymentStatus: "not_funded",
    designFee: 3_600_000,
    startedAt: isoInDays(-18),
    lastUpdated: isoInDays(-3),
    includedRevisions: 2,
    revisionRoundsUsed: 0,
    clientReviewPeriodDays: 5,
    finalDecisionMaker: "Musa Bello",
    brief: gwarinpaBrief,
    agreement: {
      id: "agr-gwarinpa",
      appointment: "design_only",
      status: "in_preparation",
      totalDesignFee: 3_600_000,
      includedRevisions: 2,
      designTimelineWeeks: 10,
      clientReviewPeriodDays: 5,
      finalDecisionMaker: "Musa Bello",
      deliverables: [
        "Concept design",
        "Floor plans",
        "Elevations & sections",
        "3D exterior renders",
        "Construction drawings",
      ],
      exclusions: [...DESIGN_ONLY_EXCLUSIONS],
      differences: [
        {
          id: "diff-gw-1",
          topic: "Number of 3D renders",
          briefSays: "Client expects renders of every elevation (4).",
          proposalSays: "Proposal includes 2 exterior renders.",
          resolution: null,
        },
        {
          id: "diff-gw-2",
          topic: "Design timeline",
          briefSays: "Client asked for 10 weeks.",
          proposalSays: "Studio proposed 12 weeks.",
          resolution: null,
        },
      ],
      confirmedSteps: ["summary", "scope"],
      preparedFromProposalId: "prop-gwarinpa",
    },
    deliverables: [
      {
        id: "del-gw-1",
        name: "Project brief confirmation",
        phase: "brief_review",
        status: "locked",
        dueDate: null,
        revisionRound: null,
        clientStatus: "not_applicable",
        lockedReason: "Requires a signed agreement",
        files: [],
      },
    ],
    approvals: [{ id: "app-gw-1", stage: "project_brief", status: "not_submitted" }],
    revisions: [],
    payments: [
      { id: "pm-gw-1", name: "Brief confirmation", amount: 540_000, status: "not_funded" },
      { id: "pm-gw-2", name: "Concept presentation", amount: 900_000, status: "not_funded" },
      { id: "pm-gw-3", name: "Developed design", amount: 1_080_000, status: "not_funded" },
      { id: "pm-gw-4", name: "Construction drawings", amount: 1_080_000, status: "not_funded" },
    ],
    documents: [],
    conversationSummaries: [],
  },

  /* 5 — Blocked: a milestone is in dispute, so nothing can progress. */
  {
    id: "ap-kubwa",
    title: "Kubwa Terrace Units",
    clientName: "Hauwa Sani",
    clientVerified: false,
    location: "Kubwa, Abuja",
    imageUrl: IMG.investment,
    origin: "off_platform",
    appointment: "design_only",
    phase: "client_concept_review",
    status: "project_blocked",
    nextAction: "Amana is reviewing the disputed concept milestone",
    responsibleParty: "amana",
    dueDate: null,
    paymentStatus: "pending",
    designFee: 2_400_000,
    startedAt: isoInDays(-52),
    lastUpdated: isoInDays(-7),
    blockedReason:
      "Concept milestone is in dispute — Amana is reviewing before any further work is released.",
    includedRevisions: 1,
    revisionRoundsUsed: 1,
    clientReviewPeriodDays: 7,
    finalDecisionMaker: "Hauwa Sani",
    brief: kubwaBrief,
    agreement: {
      id: "agr-kubwa",
      appointment: "design_only",
      status: "signed",
      totalDesignFee: 2_400_000,
      includedRevisions: 1,
      designTimelineWeeks: 8,
      clientReviewPeriodDays: 7,
      finalDecisionMaker: "Hauwa Sani",
      deliverables: ["Concept design", "Floor plans", "Construction drawings"],
      exclusions: [...DESIGN_ONLY_EXCLUSIONS],
      differences: [],
      confirmedSteps: [
        "summary",
        "scope",
        "differences",
        "deliverables",
        "revisions",
        "fees",
        "timeline",
        "authority",
        "exclusions",
        "sign",
      ],
      preparedFromProposalId: null,
      signedAt: isoInDays(-50),
    },
    deliverables: [
      {
        id: "del-kb-1",
        name: "Concept design pack",
        phase: "client_concept_review",
        status: "submitted",
        dueDate: isoInDays(-14),
        revisionRound: 1,
        clientStatus: "pending",
        files: [
          {
            id: "f-kb-1",
            name: "Concept pack.pdf",
            format: "PDF",
            sizeLabel: "5.1 MB",
            uploadedAt: isoInDays(-15),
          },
        ],
        submittedAt: isoInDays(-15),
      },
    ],
    approvals: [
      {
        id: "app-kb-1",
        stage: "project_brief",
        status: "approved",
        submittedAt: isoInDays(-48),
        decidedAt: isoInDays(-46),
        decidedBy: "Hauwa Sani",
      },
      {
        id: "app-kb-2",
        stage: "concept_design",
        status: "approval_overdue",
        submittedAt: isoInDays(-15),
        dueDate: isoInDays(-8),
      },
    ],
    revisions: [],
    payments: [
      {
        id: "pm-kb-1",
        name: "Brief confirmation",
        amount: 360_000,
        status: "paid",
        fundedAt: isoInDays(-50),
        earnedAt: isoInDays(-46),
        paidAt: isoInDays(-44),
      },
      {
        id: "pm-kb-2",
        name: "Concept presentation",
        amount: 600_000,
        status: "disputed",
        fundedAt: isoInDays(-40),
        disputeReason: "Client says the unit count does not match the brief.",
      },
      { id: "pm-kb-3", name: "Construction drawings", amount: 1_440_000, status: "not_funded" },
    ],
    documents: [],
    conversationSummaries: [],
  },

  /* 6 — Closed, for the completed-projects card and the portfolio. */
  {
    id: "ap-maitama",
    title: "Maitama Villa",
    clientName: "Ibrahim Yusuf",
    clientVerified: true,
    location: "Maitama, Abuja",
    imageUrl: IMG.villa,
    origin: "invited_client",
    appointment: "design_only",
    phase: "project_closed",
    status: "project_completed",
    nextAction: "No further action — project closed",
    responsibleParty: "amana",
    dueDate: null,
    paymentStatus: "paid",
    designFee: 9_000_000,
    startedAt: isoInDays(-230),
    lastUpdated: isoInDays(-30),
    includedRevisions: 2,
    revisionRoundsUsed: 2,
    clientReviewPeriodDays: 5,
    finalDecisionMaker: "Ibrahim Yusuf",
    brief: maitamaBrief,
    agreement: {
      id: "agr-maitama",
      appointment: "design_only",
      status: "signed",
      totalDesignFee: 9_000_000,
      includedRevisions: 2,
      designTimelineWeeks: 16,
      clientReviewPeriodDays: 5,
      finalDecisionMaker: "Ibrahim Yusuf",
      deliverables: ["Concept design", "Construction drawings", "3D exterior renders"],
      exclusions: [...DESIGN_ONLY_EXCLUSIONS],
      differences: [],
      confirmedSteps: [
        "summary",
        "scope",
        "differences",
        "deliverables",
        "revisions",
        "fees",
        "timeline",
        "authority",
        "exclusions",
        "sign",
      ],
      preparedFromProposalId: null,
      signedAt: isoInDays(-226),
    },
    deliverables: [
      {
        id: "del-mt-1",
        name: "Final architectural drawings",
        phase: "final_delivery",
        status: "complete",
        dueDate: isoInDays(-40),
        revisionRound: 2,
        clientStatus: "approved",
        files: [],
        submittedAt: isoInDays(-45),
        approvedAt: isoInDays(-40),
      },
    ],
    approvals: [
      {
        id: "app-mt-1",
        stage: "final_drawings",
        status: "approved",
        submittedAt: isoInDays(-45),
        decidedAt: isoInDays(-40),
        decidedBy: "Ibrahim Yusuf",
      },
    ],
    revisions: [],
    payments: [
      {
        id: "pm-mt-1",
        name: "Final delivery",
        amount: 9_000_000,
        status: "paid",
        fundedAt: isoInDays(-220),
        earnedAt: isoInDays(-40),
        paidAt: isoInDays(-34),
      },
    ],
    documents: [
      {
        id: "pdoc-mt-1",
        name: "Final drawing set.zip",
        format: "ZIP",
        category: "drawing",
        uploadedAt: isoInDays(-45),
        uploadedBy: "Okumagba Design Studio",
      },
    ],
    conversationSummaries: [],
  },
];

/* ------------------------------------------------------------------ *
 * Opportunities
 * ------------------------------------------------------------------ */

const banexBrief: ClientBrief = {
  id: "brief-banex",
  submittedAt: isoInDays(-9),
  projectType: "Commercial",
  siteLocation: "Banex Junction, Wuse 2, Abuja",
  clientLocation: "Abuja, Nigeria",
  bedrooms: null,
  floors: 3,
  requiredSpaces: [
    "Ground-floor retail",
    "Two floors of open-plan office",
    "Server room",
    "Rooftop plant",
    "40-space car park",
  ],
  preferredStyle: "Modern Minimalist",
  budgetRange: "₦150M – ₦300M",
  inspirationImages: [IMG.minimalist, IMG.luxury],
  desiredTimeline: "Drawings in 12 weeks",
  specialRequests: "Facade must accommodate tenant signage without redesign.",
  surveyPlan: {
    id: "doc-bx-survey",
    name: "Survey plan — Banex.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-9),
  },
  documents: [
    {
      id: "doc-bx-zoning",
      name: "AMAC zoning letter.pdf",
      kind: "land_document",
      uploadedAt: isoInDays(-8),
    },
  ],
  localRepresentative: null,
  clientVerified: true,
};

const lekkiBrief: ClientBrief = {
  id: "brief-lekki",
  submittedAt: isoInDays(-4),
  projectType: "Family home",
  siteLocation: "Lekki Phase 1, Lagos",
  clientLocation: "Toronto, Canada",
  bedrooms: 5,
  floors: 2,
  requiredSpaces: ["Family lounge", "Home cinema", "Pool deck", "Staff quarters"],
  preferredStyle: "Contemporary Luxury",
  budgetRange: "₦300M+",
  inspirationImages: [IMG.luxury, IMG.villa],
  desiredTimeline: "Design in 16 weeks",
  specialRequests: "Client visits Nigeria twice a year — reviews must be remote-friendly.",
  surveyPlan: {
    id: "doc-lk-survey",
    name: "Survey plan — Lekki Phase 1.pdf",
    kind: "survey_plan",
    uploadedAt: isoInDays(-4),
  },
  documents: [],
  localRepresentative: "Seyi Okoro (cousin, Lagos)",
  clientVerified: true,
};

const asabaBrief: ClientBrief = {
  id: "brief-asaba",
  submittedAt: isoInDays(-2),
  projectType: "Community",
  siteLocation: "Asaba, Delta State",
  clientLocation: "Asaba, Delta State",
  bedrooms: null,
  floors: 1,
  requiredSpaces: ["600-seat hall", "Crèche", "Offices", "Parking"],
  preferredStyle: "Classical",
  budgetRange: "₦50M – ₦150M",
  inspirationImages: [IMG.classical],
  desiredTimeline: "Flexible",
  specialRequests: "Committee decisions can be slow — expect longer review periods.",
  surveyPlan: null,
  documents: [],
  localRepresentative: null,
  clientVerified: false,
};

export const MOCK_OPPORTUNITIES: DesignOpportunity[] = [
  {
    id: "opp-banex",
    projectName: "Banex Office Project",
    clientName: "Ngozi Eze",
    location: "Wuse 2, Abuja",
    propertyType: "Commercial — 3-storey office",
    budgetRange: "₦150M – ₦300M",
    style: "Modern Minimalist",
    requiredDeliverables: [
      "Concept design",
      "Floor plans",
      "Elevations & sections",
      "3D exterior renders",
      "Construction drawings",
    ],
    targetTimeline: "12 weeks",
    proposalDeadline: isoInDays(0),
    architectsBidding: 6,
    clientVerified: true,
    postedAt: isoInDays(-9),
    imageUrl: IMG.minimalist,
    status: "open",
    brief: banexBrief,
  },
  {
    id: "opp-lekki",
    projectName: "Lekki Phase 1 Residence",
    clientName: "Chioma Balogun",
    location: "Lekki, Lagos",
    propertyType: "Residential — 5-bedroom duplex",
    budgetRange: "₦300M+",
    style: "Contemporary Luxury",
    requiredDeliverables: [
      "Concept design",
      "Floor plans",
      "3D exterior renders",
      "3D interior renders",
      "Construction drawings",
    ],
    targetTimeline: "16 weeks",
    proposalDeadline: isoInDays(6),
    architectsBidding: 3,
    clientVerified: true,
    postedAt: isoInDays(-4),
    imageUrl: IMG.luxury,
    status: "open",
    brief: lekkiBrief,
  },
  {
    id: "opp-asaba",
    projectName: "Asaba Community Hall",
    clientName: "St. Peter's Development Committee",
    location: "Asaba, Delta State",
    propertyType: "Community — assembly hall",
    budgetRange: "₦50M – ₦150M",
    style: "Classical",
    requiredDeliverables: ["Concept design", "Floor plans", "Construction drawings"],
    targetTimeline: "Flexible",
    proposalDeadline: isoInDays(12),
    architectsBidding: 1,
    clientVerified: false,
    postedAt: isoInDays(-2),
    imageUrl: IMG.classical,
    status: "saved",
    brief: asabaBrief,
  },
];

/* ------------------------------------------------------------------ *
 * Proposals
 * ------------------------------------------------------------------ */

const STANDARD_DELIVERABLES = [
  "Concept design",
  "Floor plans",
  "Elevations & sections",
  "3D exterior renders",
  "Construction drawings",
];

export const MOCK_ARCHITECT_PROPOSALS: ArchitectProposal[] = [
  {
    id: "prop-gwarinpa",
    opportunityId: null,
    projectTitle: "Gwarinpa Duplex",
    clientName: "Musa Bello",
    designFee: 3_600_000,
    timelineWeeks: 12,
    deliverables: STANDARD_DELIVERABLES,
    revisionsIncluded: 2,
    renders3d: 2,
    fileFormats: ["PDF", "DWG"],
    planningApprovalAssistance: true,
    consultantCoordination: false,
    optionalServices: ["Interior design package"],
    exclusions: ["Construction supervision", "Statutory approval fees"],
    assumptions: "Survey plan is accurate and the plot is free of encumbrance.",
    validityDays: 30,
    submittedAt: isoInDays(-20),
    status: "selected",
  },
  {
    id: "prop-eze",
    opportunityId: "opp-banex",
    projectTitle: "Banex Office Project",
    clientName: "Ngozi Eze",
    designFee: 14_500_000,
    timelineWeeks: 12,
    deliverables: STANDARD_DELIVERABLES,
    revisionsIncluded: 2,
    renders3d: 3,
    fileFormats: ["PDF", "DWG", "JPG"],
    planningApprovalAssistance: true,
    consultantCoordination: true,
    optionalServices: ["Walkthrough animation"],
    exclusions: ["Construction supervision", "Structural engineering design"],
    assumptions: "Zoning approval for three floors is already in place.",
    validityDays: 21,
    submittedAt: isoInDays(-3),
    status: "clarification_requested",
    clientNote: "Can you confirm whether the fee covers the tenant signage strategy?",
  },
  {
    id: "prop-owerri",
    opportunityId: null,
    projectTitle: "Owerri Family Compound",
    clientName: "Obi Family",
    designFee: 6_200_000,
    timelineWeeks: 14,
    deliverables: STANDARD_DELIVERABLES,
    revisionsIncluded: 2,
    renders3d: 2,
    fileFormats: ["PDF"],
    planningApprovalAssistance: false,
    consultantCoordination: false,
    optionalServices: [],
    exclusions: ["Construction supervision"],
    assumptions: "Client provides an up-to-date survey plan.",
    validityDays: 14,
    // Submitted long enough ago that the validity period has lapsed.
    submittedAt: isoInDays(-40),
    status: "submitted",
  },
  {
    id: "prop-adeniyi",
    opportunityId: null,
    projectTitle: "Adeniyi Residence",
    clientName: "Tunde Adeniyi",
    designFee: 4_800_000,
    timelineWeeks: 12,
    deliverables: STANDARD_DELIVERABLES,
    revisionsIncluded: 2,
    renders3d: 2,
    fileFormats: ["PDF", "DWG"],
    planningApprovalAssistance: false,
    consultantCoordination: false,
    optionalServices: [],
    exclusions: ["Construction supervision"],
    assumptions: "Soil conditions are suitable for a strip foundation.",
    validityDays: 30,
    submittedAt: isoInDays(-66),
    status: "selected",
  },
  {
    id: "prop-idemeto",
    opportunityId: null,
    projectTitle: "Idemeto Family Residence",
    clientName: "Ema Umoh",
    designFee: 7_500_000,
    timelineWeeks: 14,
    deliverables: STANDARD_DELIVERABLES,
    revisionsIncluded: 2,
    renders3d: 3,
    fileFormats: ["PDF", "DWG", "JPG"],
    planningApprovalAssistance: true,
    consultantCoordination: true,
    optionalServices: [],
    exclusions: ["Construction supervision"],
    assumptions: "Local representative can attend site meetings on the client's behalf.",
    validityDays: 30,
    submittedAt: isoInDays(-90),
    status: "selected",
  },
];

/* ------------------------------------------------------------------ *
 * Messages
 * ------------------------------------------------------------------ */

export const MOCK_PROJECT_MESSAGES: ProjectMessage[] = [
  {
    id: "msg-1",
    projectId: "ap-idemeto",
    type: "revision",
    author: "Ema Umoh",
    authorRole: "client",
    body: "I have added my comments on the concept plans. The kitchen is the main one for me.",
    createdAt: isoInDays(-2),
    read: false,
  },
  {
    id: "msg-2",
    projectId: "ap-riverview",
    type: "deliverable",
    author: "Adaeze Nwankwo",
    authorRole: "client",
    body: "Travelling this week — I will review the developed design when I land.",
    createdAt: isoInDays(-4),
    read: true,
  },
  {
    id: "msg-3",
    projectId: "ap-gwarinpa",
    type: "agreement",
    author: "Musa Bello",
    authorRole: "client",
    body: "Please confirm the number of renders before I sign.",
    createdAt: isoInDays(-3),
    read: false,
  },
  {
    id: "msg-4",
    projectId: "ap-kubwa",
    type: "payment",
    author: "Amana",
    authorRole: "amana",
    body: "A dispute has been opened on the concept milestone. Funds remain protected while we review.",
    createdAt: isoInDays(-7),
    read: true,
  },
  {
    id: "msg-5",
    projectId: "ap-adeniyi",
    type: "general",
    author: "Tunde Adeniyi",
    authorRole: "client",
    body: "Looking forward to the developed design set.",
    createdAt: isoInDays(-6),
    read: true,
  },
];

export const MOCK_CONVERSATION_SUMMARIES: ConversationSummary[] =
  MOCK_ARCHITECT_PROJECTS.flatMap((project) => project.conversationSummaries);

/* ------------------------------------------------------------------ *
 * Activity & notifications
 * ------------------------------------------------------------------ */

export const MOCK_ARCHITECT_ACTIVITY: ArchitectActivity[] = [
  {
    id: "act-1",
    text: "Ema Umoh returned comments on the Idemeto concept plans",
    createdAt: isoInDays(-1),
    tone: "warning",
  },
  {
    id: "act-2",
    text: "₦1,200,000 became available for withdrawal — Adeniyi concept presentation",
    createdAt: isoInDays(-2),
    tone: "success",
  },
  {
    id: "act-3",
    text: "Developed design set submitted to River View Apartments",
    createdAt: isoInDays(-5),
    tone: "info",
  },
  {
    id: "act-4",
    text: "Amana opened a review on the Kubwa concept milestone",
    createdAt: isoInDays(-7),
    tone: "warning",
  },
  {
    id: "act-5",
    text: "Proposal submitted for Banex Office Project",
    createdAt: isoInDays(-3),
    tone: "info",
  },
];

export const MOCK_ARCHITECT_NOTIFICATIONS: ArchitectNotification[] = [
  {
    id: "n-1",
    type: "revision_requested",
    title: "Revision requested",
    body: "Ema Umoh requested changes to the Idemeto concept floor plans.",
    read: false,
    createdAt: isoInDays(-1),
    targetView: "project-detail",
    targetProjectId: "ap-idemeto",
    targetTab: "feedback",
  },
  {
    id: "n-2",
    type: "payment_available",
    title: "Payment available for withdrawal",
    body: "₦1,200,000 from the Adeniyi concept presentation is ready to withdraw.",
    read: false,
    createdAt: isoInDays(-2),
    targetView: "payments",
  },
  {
    id: "n-3",
    type: "proposal_deadline",
    title: "Proposal deadline is today",
    body: "Banex Office Project closes for bids today.",
    read: false,
    createdAt: isoInDays(0),
    targetView: "opportunities",
  },
  {
    id: "n-4",
    type: "agreement_ready",
    title: "Agreement ready to prepare",
    body: "You were selected for Gwarinpa Duplex. Two differences still need resolving.",
    read: true,
    createdAt: isoInDays(-3),
    targetView: "project-detail",
    targetProjectId: "ap-gwarinpa",
    targetTab: "agreement",
  },
  {
    id: "n-5",
    type: "deliverable_due",
    title: "Deliverable due tomorrow",
    body: "The Adeniyi developed design set is due tomorrow.",
    read: true,
    createdAt: isoInDays(-1),
    targetView: "project-detail",
    targetProjectId: "ap-adeniyi",
    targetTab: "deliverables",
  },
];

/* ------------------------------------------------------------------ *
 * Team & portfolio
 * ------------------------------------------------------------------ */

export const MOCK_TEAM: TeamMember[] = [
  {
    id: "tm-1",
    name: "Chidi Okumagba",
    role: "Principal architect",
    email: "chidi@okumagba.design",
    status: "active",
    assignedProjectIds: ["ap-idemeto", "ap-riverview", "ap-gwarinpa"],
  },
  {
    id: "tm-2",
    name: "Amaka Eze",
    role: "Project architect",
    email: "amaka@okumagba.design",
    status: "active",
    assignedProjectIds: ["ap-adeniyi"],
  },
  {
    id: "tm-3",
    name: "Femi Balogun",
    role: "Visualiser",
    email: "femi@okumagba.design",
    status: "invited",
    assignedProjectIds: [],
  },
];

export const MOCK_PORTFOLIO: PortfolioItem[] = [
  { id: "pf-1", title: "Maitama Villa", category: "Residential", year: "2025", imageUrl: IMG.villa },
  { id: "pf-2", title: "Asokoro Terraces", category: "Residential", year: "2024", imageUrl: IMG.duplexSuplex },
  { id: "pf-3", title: "Wuse Retail Block", category: "Commercial", year: "2024", imageUrl: IMG.minimalist },
  { id: "pf-4", title: "Enugu Family Compound", category: "Residential", year: "2023", imageUrl: IMG.multiFamily },
];

export const MOCK_ARCHITECT_REVIEWS = [
  {
    id: "rv-1",
    clientName: "Ibrahim Yusuf",
    projectTitle: "Maitama Villa",
    rating: 5,
    comment: "Clear communication and excellent drawings throughout the appointment.",
    createdAt: isoInDays(-32),
  },
  {
    id: "rv-2",
    clientName: "Adaeze Nwankwo",
    projectTitle: "River View Apartments",
    rating: 5,
    comment: "Handled a complicated unit mix without ever losing the plot.",
    createdAt: isoInDays(-58),
  },
];
